from matrix_table_consumer import MatrixTableConsumer


test_text = [
    {
        "CHROM": "chr1",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 1,
        "QUAL": 1,
    },
    {
        "CHROM": "chr1",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 2,
        "QUAL": 2,
    },
    {
        "CHROM": "chr1",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 3,
        "QUAL": 3,
    },
    {
        "CHROM": "chr2",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 4,
        "QUAL": 4,
    },
    {
        "CHROM": "chr2",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 5,
        "QUAL": 5,
    },
    {
        "CHROM": "chr3",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 6,
        "QUAL": 6,
    },
    {
        "CHROM": "chr4",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 7,
        "QUAL": 7,
    },
    {
        "CHROM": "chr4",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 8,
        "QUAL": 8,
    },
    {
        "CHROM": "chr4",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 9,
        "QUAL": 9,
    },
    {
        "CHROM": "chr5",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 10,
        "QUAL": 10,
    },
    {
        "CHROM": "chr6",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 11,
        "QUAL": 11,
    },
    {
        "CHROM": "chr6",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 12,
        "QUAL": 12,
    },
    {
        "CHROM": "chr6",
        "ID": ".",
        "REF": "C",
        "ALT": "T",
        "FILTER": "PASS",
        "INFO": ".",
        "POS": 13,
        "QUAL": 13,
    },
]


def test_collect_all() -> None:
    vcf_path = "../matrix_table_consumer/data/collect/test1.vcf"

    consumer = MatrixTableConsumer(vcf_path=vcf_path, reference_genome="GRCh37")

    rows = consumer.collect_all(num_cpu=1)
    assert rows == test_text, rows
